# Define if testing MySQL 5 database backend
DEFINES+=MYSQL_TEST
DEFINES+=MYSQL_USERNAME=\\\"\\\"
DEFINES+=MYSQL_PASSWORD=\\\"\\\"
DEFINES+=MYSQL_ROOT_PASSWORD=\\\"\\\"
DEFINES+=MYSQL_HOST=\\\"\\\"
DEFINES+=MYSQL_PORT=3306
DEFINES+=MYSQL_DB=\\\"\\\"

CONFIG+=local
